/* Environment-based configuration */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "eielkzwmadqvgofvxumr"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZWxrendtYWRxdmdvZnZ4dW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyODY3ODksImV4cCI6MjA3ODg2Mjc4OX0.7ZVMTxq8Zaw25gGd2HW057cf5z568tHyOrbDUeudzF8"